# Generated by Django 4.2.4 on 2023-08-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('make', models.CharField(max_length=20)),
                ('machine_model', models.CharField(max_length=20)),
                ('serial', models.IntegerField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('part_num', models.CharField(max_length=20, unique=True)),
                ('rate', models.IntegerField(max_length=5)),
                ('total_quantity', models.IntegerField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.TimeField()),
                ('item_count', models.IntegerField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=15)),
                ('cell', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('pieces', models.IntegerField(max_length=5)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productionline')),
            ],
        ),
        migrations.AddField(
            model_name='productionline',
            name='working_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shift'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_per_hour', models.IntegerField(max_length=5)),
                ('quantity', models.IntegerField(max_length=10)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productionline')),
                ('products', models.ManyToManyField(to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('worker_number', models.IntegerField(max_length=15, unique=True)),
                ('working_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.productionline'),
        ),
    ]
