# Generated by Django 4.2.4 on 2023-08-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='worker_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_per_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productioninfo',
            name='item_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='cell',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='pieces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='number',
            field=models.IntegerField(),
        ),
    ]
