# Generated by Django 4.2.4 on 2023-08-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_machine_serial_alter_operator_worker_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='working_machine',
        ),
        migrations.AddField(
            model_name='operator',
            name='working_line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.productionline'),
        ),
        migrations.AddField(
            model_name='productioninfo',
            name='line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.productionline'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='making_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
