# Generated by Django 4.2.4 on 2023-09-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_downtime_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speedloss',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speedloss', to='api.shift')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
