# Generated by Django 4.2.4 on 2023-09-21 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_speedloss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='title',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='production',
        ),
        migrations.AddField(
            model_name='scrap',
            name='minute',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrap',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to='api.shift'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrap',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
