# Generated by Django 4.2.4 on 2023-08-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_operator_working_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.productionline'),
        ),
    ]
