# Generated by Django 4.2.4 on 2023-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='number',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_number',
            field=models.IntegerField(choices=[('First', 1), ('Second', 2)], default=1),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(),
        ),
    ]
