# Generated by Django 4.2.4 on 2023-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_shift_number_shift_shift_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_number',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')], default=1),
        ),
    ]
