# Generated by Django 4.2.4 on 2023-08-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shift_shift_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
        migrations.AlterField(
            model_name='productionline',
            name='working_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='api.shift'),
        ),
    ]
