# Generated by Django 4.2.4 on 2023-08-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
        migrations.AlterField(
            model_name='machine',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='api.productionline'),
        ),
    ]
