# Generated by Django 4.2.4 on 2023-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='cell',
            field=models.IntegerField(null=True),
        ),
    ]
