# Generated by Django 4.2.4 on 2023-08-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_machine_name_alter_machine_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioninfo',
            name='line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='api.productionline'),
        ),
    ]
