# Generated by Django 4.2.4 on 2023-08-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_operator_working_line_alter_scrap_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='target_per_hour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='making_product',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='working_shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start',
        ),
        migrations.AddField(
            model_name='operator',
            name='working_shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operatorS', to='api.shift'),
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.shift'),
        ),
        migrations.AddField(
            model_name='productioninfo',
            name='shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='api.shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='making_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='shift',
            name='on_line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='api.productionline'),
        ),
        migrations.AlterField(
            model_name='order',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderL', to='api.productionline'),
        ),
    ]
