# Generated by Django 4.2.4 on 2023-08-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_machine_status_remove_order_target_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='making_product',
        ),
    ]
