# Generated by Django 4.2.4 on 2023-08-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_shift_making_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='working_shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='api.shift'),
        ),
    ]
