# Generated by Django 4.2.4 on 2023-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_operator_working_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninfo',
            name='hour',
            field=models.TimeField(null=True),
        ),
    ]
