# Generated by Django 4.2.4 on 2023-09-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productioninfo_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productioninfo',
            options={'ordering': ['minute']},
        ),
    ]
