# Generated by Django 4.2.4 on 2023-09-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_productioninfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='working_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='api.productionline'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='working_shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='api.shift'),
        ),
    ]
