# Generated by Django 4.2.4 on 2023-09-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_operator_working_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='working_line',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='api.productionline'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='working_shift',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='api.shift'),
        ),
    ]
