# Generated by Django 4.2.4 on 2023-09-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_operator_working_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='working_line',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='working_shift',
        ),
    ]
