# Generated by Django 4.2.4 on 2023-09-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_shift_operators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='operators',
            field=models.ManyToManyField(blank=True, to='api.operator'),
        ),
    ]
