# Generated by Django 4.2.4 on 2023-09-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_shift_operators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['last_name']},
        ),
    ]
